### ISSUE TITLE
CSS Background Not Fully Covering Text Area

### ISSUE THREAD

**Issue by Grim4Reaper** [GrimReaper2654/Huynh-Dating-Simulator-EXTREME#5]
![image](https://user-images.githubusercontent.com/85726678/230025622-40dc221a-a668-4822-8834-e7162ffca087.png)

The background of pink does not cover the entire area.

**Comment by GrimReaper2654** [comment]
blame abi

**Comment by GrimReaper2654** [comment]
I fixed it
