### ISSUE TITLE
Not being able to continue

### ISSUE THREAD

**Issue by Grim4Reaper** [GrimReaper2654/Huynh-Dating-Simulator-EXTREME#6]
You can't get past the introduce your self part to the next choice.

Once you click continue here, it removes all text.

Before
![image](https://user-images.githubusercontent.com/85726678/230030542-a86cf955-f9cb-4d6b-9d69-621fcca6588a.png)

After
![image](https://user-images.githubusercontent.com/85726678/230030741-792dc39e-a811-4e8d-9243-7064dea7b0af.png)

**Comment by GrimReaper2654** [comment]
THat route isn't complete yet lol

**Comment by Grim4Reaper** [comment]
But it has content in the code

**Comment by GrimReaper2654** [comment]
I fixed

**Comment by GrimReaper2654** [comment]
anyways, I did fix it but forgot to push the code to github
